name: "Dong Chat"
description: "AI code reviewer"
inputs:
  GITHUB_TOKEN:
    required: true
  OPENAI_API_KEY:
    required: true
  OPENAI_API_MODEL:
    required: false
  exclude:
    required: false
runs:
  using: "composite"
  steps:
    - run: echo "Hello from Dong Chat"
